#ifndef SRC_MODELS_MEMENTO_MEMENTORESTORERESULT_H_
#define SRC_MODELS_MEMENTO_MEMENTORESTORERESULT_H_

namespace Mastermind {

enum class MementoRestoreResult {
    OK = 0,
    SECRET_COMBINATION_ERROR,
    PROPOSED_COMBINATION_ERROR,
};

}

#endif /* SRC_MODELS_MEMENTO_MEMENTORESTORERESULT_H_ */
